### ISSUE TITLE
Help with syntex

### ISSUE THREAD

**Issue by CTokkie** [CTokkie/code#2]
Having trouble with the syntex for the Assessment C lines 46 to 62

I'll look up the logical error i have with Fibonacci and see if i can have it working with that

**Comment by CTokkie** [comment]
// Assessment - Part C
// func simulatedBankReturnOnInterest(  initalInvestment:Int , numberYears:Int, interestRate:Int , interestEarned:Int) -> Int
// {
	 
// 		for simulatedBankReturnOnInterest 1...numberYears 
// 			{
// 			(  interestEarned = initalInvestment + interestEarned ) * (1 + interestRate) / 100 
// 			}
			

// 	return initalInvestment:Int + interestEarned:Int
// }
// var feelsLikeThisDoneIncorrectly:Int = simulatedBankReturnOnInterest ( initalInvestment: 1000 , numberYears: 10 , interestRate: 20, InterestEarned: 0)
// print ( "Your total balance \(feelsLikeThisDoneIncorrectly)")

**Comment by djulzz** [comment]
I’ll get back to you later, but I am now aware of the issue

**Comment by CTokkie** [comment]
Thank you, something I was worried about which i would messaged you through canvas, if i didn't hear from you today.  

The 2nd message though was more due to me not knowing how to link the specific swift file being the week 2 deliverable one.

**Comment by CTokkie** [comment]
I managed to figure it it out
